name: happytails
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  http: ^1.2.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/lotties/
  uses-material-design: true
